[workspace]
members = ["bpfd", "bpfd-api", "bpfd-common", "bpfctl","bpfd-agent", "bpfd-k8s-api", "xtask"]

[patch.crates-io]
aya = {git = "https://github.com/aya-rs/aya", branch="main"}
# Use this patch until https://github.com/krustlet/oci-distribution/pull/43 Merges
oci-distribution = {git = "https://github.com/astoycos/oci-distribution", branch="main"}
