site_name: bpfd
repo_url: https://github.com/bpfd-dev/bpfd
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
site_dir: site

theme:
  name: material
  language: en
  logo: img/bpfd_icon.svg
  favicon: img/bpd_icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Home: index.md
  - Community:
    - Meetings: ../MEETINGS.md
    - Governacne: ../GOVERNANCE.md
    - Code of Conduct: ../CODE_OF_CONDUCT.md
    - Maintainers: ../MAINTAINERS.md
    - Security: ../SECURITY.md
  - Getting Started:
    - Setup and Building: bpfd/building-bpfd.md
    - Bpfd on Linux Tutorial: bpfd/tutorial.md
    - bpfctl Guide: bpfctl-guide.md
    - Example eBPF Programs: examples/example-bpf.md
    - Deploying Example eBPF Programs On Local Host: examples/example-bpf-local.md
    - Deploying Example eBPF Programs On Kubernetes: examples/example-bpf-k8s.md
  - Developers:
    - Contributing: ../CONTRIBUTING.md
    - Reviewing Guide: ../REVIEWING.md
    - bpfd-operator Quick start: bpfd-operator/quick-start.md
    - bpfd-operator Developer Guide: bpfd-operator/developing.md
    - Kubernetes CRD API-Reference: bpfd-operator/api-spec.md
    - eBPF Bytecode Image Specifications: shipping-bytecode.md
    - BPFD Container Images: bpfd/image-build.md
    - Linux Capabilities: bpfd/linux-capabilities.md
    - Logging: logging.md
    - Configuration: bpfd/configuration.md

plugins:
  - search

copyright: Copyright &copy; 2021-2023 The bpfd contributors
