site_name: bpfd
repo_url: https://github.com/bpfd-dev/bpfd
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css
site_dir: site

theme:
  name: material
  language: en
  logo: img/bpfd_icon.svg
  favicon: img/bpd_icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Home: index.md
  - Bpfd:
    - Tutorial: bpfd/tutorial.md
    - Configuration: bpfd/configuration.md
    - Setup and Building: bpfd/building-bpfd.md
    - BPFD Container Images: bpfd/image-build.md
    - Linux Capabilities: bpfd/linux-capabilities.md
  - How To Deploy Bpfd on Kubernetes: 
    - Quick start: bpfd-operator/intro.md
    - Development: bpfd-operator/developing.md
    - API-Reference: api-spec.md
  - Examples:
    - Example BPF Programs: examples/example-bpf.md
  - Shipping Bpf Programs in Container Images:
    - EBPF Bytecode Image Specifications: shipping-bytecode.md



plugins:
  - search

copyright: Copyright &copy; 2021-2023 The bpfd contributors
