site_name: bpfd
repo_url: https://github.com/bpfd-dev/bpfd
edit_uri: edit/main/docs
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: en
  logo: img/bpfd_icon.svg
  favicon: img/bpd_icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Home:
    - index.md
    - Tutorial: tutorial.md
    - Configuration: configuration.md
    - Setup and Building bpfd: building-bpfd.md
    - Example BPF Programs: example-bpf.md
    - How to Deploy bpfd on Kubernetes: k8s-deployment.md
    - BPFD Container Images: image-build.md
    - Linux Capabilities: linux-capabilities.md
    - EBPF Bytecode Image Specifications: shipping-bytecode.md

plugins:
  - search

copyright: Copyright &copy; 2021-2023 The bpfd contribtutors
