[package]
name = "bpfd"
version = "0.1.0"
edition = "2021"

[[bin]]
    name = "bpfd"
    path = "src/bin/bpfd.rs"

[[bin]]
    name = "bpfctl"
    path = "src/bin/bpfctl.rs"

[dependencies]
tonic = "0.7"
prost = "0.10"
thiserror = "1"
clap = { version = "3", features = ["derive"]}
aya = { git = "https://github.com/aya-rs/aya", branch = "main" }
tokio = { version = "1.14.0", features = ["full"] }
uuid = { version = "1.1", features = ["v4"] }
log = "0.4"
simplelog = "0.11"
bpfd-common = { path = "../bpfd-common", features=["user"] }
nix = { version = "0.24", features = [ "socket", "fs" ]}

[build-dependencies]
tonic-build = "0.7"
