[package]
name = "bpfd"
version = "0.1.0"
edition = "2021"
description = "A system daemon for loading eBPF programs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/redhat-et/bpfd"

[[bin]]
    name = "bpfd"
    path = "src/main.rs"

[lib]

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"]}
aya = "0.11"
tokio = { version = "1.21.1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
log = "0.4"
env_logger = "0.9"
systemd-journal-logger = "0.5.0"
tonic = "0.8"
bpfd-api = { version = "0.1.0", path = "../bpfd-api" }
caps = "0.5.4"
bpfd-common = { version = "0.1.0", path = "../bpfd-common", features=["user"] }
nix = { version = "0.25", features = [ "socket", "fs", "mount"]}
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
x509-certificate = "0.15"
oci-distribution = {version = "0.9.2", default-features = false, features = ["rustls-tls", "trust-dns"] }
serde_json = "1.0"
tar = "0.4"
flate2 = "1.0"
openssl = { version = "0.10.41", features = ["vendored"] }