# permissions for end users to edit BpfProgramConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: Bpfd-admin-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/part-of: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpfd-admin-role
rules:
- apiGroups:
  - bpfd.io
  resources: ["*"]
  verbs: ["*"]
