apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpfd
  namespace: kube-system
  labels:
    k8s-app: bpfd
spec:
  selector:
    matchLabels:
      name: bpfd-daemon
  template:
    metadata:
      labels:
        name: bpfd-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: bpfd-sa
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: bpfd
        image: quay.io/bpfd/bpfd:main
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env: 
          - name: RUST_LOG
            # This will eventually be configured by the operator
            valueFrom: 
              configMapKeyRef:
                name: bpfd-config
                key: bpfd.log.level
        volumeMounts:
        - name: bpf-fs
          mountPath: /sys/fs/bpf
        - name: bpfd-ca
          mountPath: /etc/bpfd/certs/ca
          readOnly: true
        - name: bpfd-cert
          mountPath: /etc/bpfd/certs/bpfd
          readOnly: true
        - name: bpfd-config 
          mountPath: /etc/bpfd/bpfd.toml
          subPath: bpfd.toml
          readOnly: true
          # These certs are missing in the scratch image to keep it small.  Mount
          # and use the host's instead.
        - name: host-ssl
          mountPath: /etc/ssl
        - name: host-bytecode
          mountPath: /etc/bpfd/bytecode
      - name: bpfd-agent 
        image: quay.io/bpfd/bpfd-agent:main
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env: 
          - name: RUST_LOG
            # This will eventually be configured by the operator
            valueFrom: 
              configMapKeyRef:
                name: bpfd-config
                key: bpfd.log.level
        volumeMounts:
        - name: bpfd-ca
          mountPath: /etc/bpfd/certs/ca
          readOnly: true
        - name: bpfd-agent-cert
          mountPath: /etc/bpfd/certs/bpfd-agent
          readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
      - name: bpfd-ca
        secret: 
          secretName: bpfd-ca
          optional: false
      - name: bpfd-cert
        secret:
          secretName: bpfd-cert-secret
          optional: false
      - name: bpfd-agent-cert
        secret: 
          secretName: bpfd-agent-cert-secret
          optional: false
      - name: bpfd-config
        configMap: 
          name: bpfd-config
      - name: host-ssl 
        hostPath: 
          path: /etc/ssl
      - name: host-bytecode
        hostPath:
          path: /etc/bpfd/bytecode
      