apiVersion: bpfd.dev/v1alpha1
kind: TcProgram
metadata:
  labels:
    app.kubernetes.io/name: tcprogram
  name: go-tc-counter-example
spec:
  bpffunctionname: stats
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    interfaces: 
    - eth0
  priority: 55
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/go-tc-counter:latest