apiVersion: bpfman.io/v1alpha1
kind: FentryProgram
metadata:
  labels:
    app.kubernetes.io/name: fentryprogram
  name: fentry-example
spec:
  bpffunctionname: fentry_test
  # Select all nodes
  nodeselector: {}
  func_name: do_unlinkat
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/fentry:latest
