name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check-license:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes@f461a46e74e5fa22e9f9599a355ab4f0ac265469

  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      ## Install perl due to https://github.com/openssl/openssl/issues/13761
      - name: Install deps
        run: |
          sudo dnf groupinstall -y c-development
          sudo dnf install -y git clang llvm protobuf-compiler cmake perl
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: libbpf/libbpf
          path: libbpf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
          override: false

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - uses: Swatinem/rust-cache@v1

      - name: Build eBPF
        run: |
          cargo xtask build-ebpf --libbpf-dir ./libbpf
      - name: Check formatting
        run: |
          cargo +nightly fmt --all -- --check

      - name: Run clippy
        run: |
          cargo +nightly clippy --all -- --deny warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo llvm-cov test --all-features -p bpfd -p bpfd-api -p bpfctl --lcov --output-path lcov.info
        env:
          RUST_BACKTRACE: full

      - name: Archive Rust code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: lcov.info
          if-no-files-found: error

  ## Build go modules
  build-go:
    runs-on: ubuntu-latest
    # k8s codegen requires this to be set
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Keep this version synced with /bpfd/bpfd-operator/scripts/verify-golint.sh
          working-directory: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd
          version: v1.51.1
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: -v --timeout 3m

      - name: Build Examples
        working-directory: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd/examples
        run: |
          go build ./...

      - name: Build Operator
        working-directory: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd/bpfd-operator
        run: make build

      - name: Verify Operator
        working-directory: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd/bpfd-operator
        run: make verify

      - name: Run Tests
        working-directory: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd/bpfd-operator
        run: make test

      - name: Archive Go code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ${{ env.GOPATH }}/src/github.com/bpfd-dev/bpfd/bpfd-operator/cover.out
          if-no-files-found: error

  basic-integration-tests:
    runs-on: ubuntu-latest
    needs: ["build", "build-go"]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get install -y git clang llvm protobuf-compiler cmake perl acl openssl pkgconf gcc-multilib

      - uses: actions/checkout@v2
        with:
          repository: libbpf/libbpf
          path: libbpf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
          override: true

      - name: Build eBPF
        run: cargo xtask build-ebpf --libbpf-dir ./libbpf

      - name: Build bpfd
        run: cargo build --verbose

      - name: Run the bpfd installer
        run: sudo ./scripts/setup.sh install

      - name: Give certs time to be created
        run: sleep 5

      - name: Verify the bpfd systemd service is active
        run: systemctl is-active bpfd

      - name: Verify the bpfctl can reach bpfd
        run: sudo bpfctl --help

      - name: Stop the bpfd systemd service
        run: sudo systemctl stop bpfd

      - name: Run integration tests
        run: cargo xtask integration-test

  kubernetes-integration-tests:
    needs: ["build", "build-go"]
    runs-on: ubuntu-latest
    env:
      BPFD_IMG: "quay.io/bpfd/bpfd:int-test"
      BPFD_AGENT_IMG: "quay.io/bpfd/bpfd-agent:int-test"
      BPFD_OPERATOR_IMG: "quay.io/bpfd/bpfd-operator:int-test"
      DOCKER_BUILDKIT: 1
      ## This should match what's found in bpfd/bpfd-operator/config/certmanager/kustomization.yaml
      CERTMANAGER_VERSION: "v1.10.1"
    steps:
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-codegen-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build images
        run: cd bpfd-operator && make build-images

      - name: run integration tests
        run: cd bpfd-operator && make test-integration

      ## Upload diagnostics if integration test step failed.
      - name: upload diagnostics
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: kubernetes-integration-test-diag
          path: /tmp/ktf-diag*
          if-no-files-found: ignore

  coverage:
    needs: ["build", "build-go"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download coverage artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./cover.out,./lcov.info
          verbose: true

  build-workflow-complete:
    needs:
      [
        "check-license",
        "build",
        "build-go",
        "coverage",
        "basic-integration-tests",
        "kubernetes-integration-tests",
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Build Complete
        run: echo "Build Complete"
