name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      ## Install perl due to https://github.com/openssl/openssl/issues/13761
      - name: Install deps
        run: |
          sudo dnf groupinstall -y c-development
          sudo dnf install -y git clang llvm protobuf-compiler cmake perl

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: libbpf/libbpf
          path: libbpf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-10
          components: rust-src
          override: true

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - uses: Swatinem/rust-cache@v1

      - name: Build eBPF
        run: |
          cargo xtask build-ebpf --libbpf-dir ./libbpf

      - name: Check formatting
        run: |
          cargo +nightly-2023-01-10 fmt --all -- --check
          pushd bpfd-ebpf
          cargo +nightly-2023-01-10 fmt --all -- --check
          popd

      - name: Run clippy
        run: |
          cargo +nightly-2023-01-10 clippy --all -- --deny warnings
          pushd bpfd-ebpf
          cargo +nightly-2023-01-10 clippy --all -- --deny warnings
          popd

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --verbose
  build-go: 
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:

      - name: Install deps
        run: |
          sudo dnf groupinstall -y c-development
          sudo dnf install -y make gcc
    
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.3"

      - name: Check formatting
        run: |
          gofmt -d -e .

      - name: Build Examples
        run: | 
          go build ./examples/go-tc-counter/
          go build ./examples/go-xdp-counter/

      - name: Build Operator
        run: | 
          cd bpfd-operator
          make build 
