name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
## Build bpfd Core
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      ## Install perl due to https://github.com/openssl/openssl/issues/13761
      - name: Install deps
        run: |
          sudo dnf groupinstall -y c-development
          sudo dnf install -y git clang llvm protobuf-compiler cmake perl

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: libbpf/libbpf
          path: libbpf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
          override: true

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - uses: Swatinem/rust-cache@v1

      - name: Build eBPF
        run: |
          cargo xtask build-ebpf --libbpf-dir ./libbpf

      - name: Check formatting
        run: |
          cargo +nightly fmt --all -- --check
          pushd bpfd-ebpf
          cargo +nightly fmt --all -- --check
          popd

      - name: Run clippy
        run: |
          cargo +nightly clippy --all -- --deny warnings
          pushd bpfd-ebpf
          cargo +nightly clippy --all -- --deny warnings
          popd

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --verbose

## Build go modules
  build-go: 
    runs-on: ubuntu-latest
    env: 
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/redhat-et/bpfd
    steps:

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/redhat-et/bpfd

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build Examples
        run: | 
          go build ./examples/go-tc-counter/
          go build ./examples/go-xdp-counter/

      ## Run linter on Examples 
      - uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # Keep this version synced with /bpfd/bpfd-operator/hack/verify-golint.sh
          version: v1.51.1
          # Optional: working directory, useful for monorepos
          working-directory: ${{ env.GOPATH }}/src/github.com/redhat-et/bpfd/examples
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          skip-build-cache: true
          # Set verbose logging
          args: -v

      - name: Build Operator
        run: | 
          cd bpfd-operator
          make build

      - name: Verify Operator Generated 
        run: |
          cd bpfd-operator
          make verify

      ## Run linter on bpfd-operator
      - uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # Keep this version synced with /bpfd/bpfd-operator/hack/verify-golint.sh
          version: v1.51.1
          # Optional: working directory, useful for monorepos
          working-directory: ${{ env.GOPATH }}/src/github.com/redhat-et/bpfd/bpfd-operator
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          skip-build-cache: true
          # Set verbose logging
          args: -v
