name: k8s-int-test

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags:
      - v*

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  kubernetes-integration-tests:
    runs-on: ubuntu-latest
    env:
      BPFMAN_IMG: quay.io/bpfman/bpfman:int-test
      BPFMAN_AGENT_IMG: quay.io/bpfman/bpfman-agent:int-test
      BPFMAN_OPERATOR_IMG: quay.io/bpfman/bpfman-operator:int-test
      XDP_PASS_PRIVATE_IMAGE_CREDS: ${{ secrets.XDP_PASS_PRIVATE_IMAGE_CREDS }}
    steps:
      - name: Check disk space
        run: df -h

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo apt-get update
          sudo eatmydata apt-get purge --auto-remove -y \
            azure-cli aspnetcore-* dotnet-* ghc-* firefox \
            google-chrome-stable \
            llvm-* microsoft-edge-stable mono-* \
            msbuild mysql-server-core-* php-* php7* \
            powershell temurin-* zulu-*
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y

      - name: Check disk space
        run: df -h

      - name: Prune Docker
        run: sudo docker system prune -a -f --volumes

      - name: Check disk space
        run: df -h

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qy \
            git \
            clang \
            llvm \
            gcc-multilib \
            libbpf-dev

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          # prettier-ignore
          go-version: '1.21' # yamllint disable-line rule:quoted-strings

      - name: cache go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-codegen-
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check disk space
        run: df -h

      ## TODO(astoycos) Currently this is just done to ensure we have coverage
      ## on all image builds. Ultimately we should be running the integration
      ## tests with these locally built bytecode images.
      - name: build example bytecode images
        run: |
          go install github.com/cilium/ebpf/cmd/bpf2go@v0.14.0
          cd examples
          make build-all-images

      - name: Check disk space
        run: df -h

      - name: build k8s operator images
        run: cd bpfman-operator && make build-images

      - name: Check disk space
        run: df -h

      - name: run cargo clean
        run: cargo clean

      - name: Check disk space
        run: df -h

      - name: run integration tests
        run: cd bpfman-operator && make test-integration

      - name: Check disk space
        run: df -h

      ## Upload diagnostics if integration test step failed.
      - name: upload diagnostics
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-integration-test-diag
          path: /tmp/ktf-diag*
          if-no-files-found: ignore

  k8s-int-test-workflow-complete:
    needs:
      [
        kubernetes-integration-tests,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: k8s-int-test Complete
        run: echo "k8s-int-test Complete"
