name: tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch: {}

#TODO Add unit testing
jobs:
  basic-integration-tests:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:

    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt-get install -y git clang llvm protobuf-compiler cmake perl acl openssl pkgconf gcc-multilib

    - uses: actions/checkout@v2
      with:
        repository: libbpf/libbpf
        path: libbpf

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src
        override: true

    - name: Install bpf-linker
      run: cargo install bpf-linker

    - name: Build eBPF
      run: cargo xtask build-ebpf --libbpf-dir ./libbpf

    - name: Build bpfd
      run: cargo build --verbose

    - name: Run the bpfd installer
      run: sudo ./scripts/setup.sh install

    - name: Give certs time to be created
      run: sleep 5

    - name: Verify the bpfd systemd service is active
      run: systemctl is-active bpfd

    - name: Verify the bpfctl can reach bpfd
      run: sudo bpfctl --help

    - name: Stop the bpfd systemd service
      run: sudo systemctl stop bpfd

    - name: Run integration tests
      run: cargo xtask integration-test

  kubernetes-integration-tests:
    runs-on: ubuntu-latest
    env:
      BPFD_IMG: "quay.io/bpfd/bpfd:int-test"
      BPFD_AGENT_IMG: "quay.io/bpfd/bpfd-agent:int-test"
      BPFD_OPERATOR_IMG: "quay.io/bpfd/bpfd-operator:int-test"
      ## This should match what's found in bpfd/bpfd-operator/config/certmanager/kustomization.yaml
      CERTMANAGER_VERSION: "v1.10.1"
    steps:

    - name: setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build images
      run: cd bpfd-operator && make build-images

    - name: run integration tests
      run: cd bpfd-operator && make test-integration

    ## Upload diagnostics if integration test step failed.
    - name: upload diagnostics
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: kubernetes-integration-test-diag
        path: /tmp/ktf-diag*
        if-no-files-found: ignore
