apiVersion: bpfd.dev/v1alpha1
kind: TcProgram
metadata:
  labels:
    app.kubernetes.io/name: tcprogram
  name: tc-pass-all-nodes
spec:
  bpffunctionname: pass
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    primarynodeinterface: true
  priority: 0
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/tc_pass:latest
  globaldata:
    GLOBAL_u8:
      - 0x01 
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
