apiVersion: bpfd.io/v1alpha1
kind: XdpProgram
metadata:
  labels:
    app.kubernetes.io/name: XdpProgram
  name: go-counter-example
spec:
  sectionname: stats
  # Select all nodes
  nodeselector:
    matchLabels: 
      deploy-ebpf: "true"
  interfaceselector:
    interface: eth0
  priority: 5
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/go-xdp-counter:latest